### ISSUE TITLE
how to solve this problem in the process of  building the pyDemFoam？

### ISSUE THREAD

**Issue by Yu-Zhang0714** [jkfurtney/PFC3D_OpenFOAM#1]
When I build the pydemfoam, the error is as follows：

demSimpleFoam.C:73:20: error: passing ‘const Foam::fvMatrix<Foam::Vector<double> >’ as ‘this’ argument discards qualifiers [-fpermissive]
       UEqn().relax();
                    ^
In file included from /home/zy/OpenFOAM/OpenFOAM-5.x/src/finiteVolume/lnInclude/fvMatrix.H:1061:0,
                 from /home/zy/OpenFOAM/OpenFOAM-5.x/src/finiteVolume/lnInclude/ddtScheme.C:29,
                 from /home/zy/OpenFOAM/OpenFOAM-5.x/src/finiteVolume/lnInclude/ddtScheme.H:342,
                 from /home/zy/OpenFOAM/OpenFOAM-5.x/src/finiteVolume/lnInclude/fvcDdt.C:28,
                 from /home/zy/OpenFOAM/OpenFOAM-5.x/src/finiteVolume/lnInclude/fvcDdt.H:205,
                 from /home/zy/OpenFOAM/OpenFOAM-5.x/src/finiteVolume/lnInclude/fvc.H:44,
                 from /home/zy/OpenFOAM/OpenFOAM-5.x/src/finiteVolume/lnInclude/fvCFD.H:8,
                 from demBaseFoam.H:2,
                 from demSimpleFoam.H:1,
                 from demSimpleFoam.C:28:
/home/zy/OpenFOAM/OpenFOAM-5.x/src/finiteVolume/lnInclude/fvMatrix.C:674:6: note:   in call to ‘void Foam::fvMatrix<Type>::relax() [with Type = Foam::Vector<double>]’
 void Foam::fvMatrix<Type>::relax()
      ^~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

And my python-dev is the latest version. So how can I solve this problem?
Thanks a lot.

**Comment by jkfurtney** [comment]
Hi, thanks for getting in touch and for your interest. This only works with OpenFOAM v3.0+ (which is a specific version of OpenFOAM, not any version 3 or greater).

**Comment by Yu-Zhang0714** [comment]
> Hi, thanks for getting in touch and for your interest. This only works with OpenFOAM v3.0+ (which is a specific version of OpenFOAM, not any version 3 or greater).

thank you very much. I am confused for a week about this question.

**Comment by Yu-Zhang0714** [comment]
> Hi, thanks for getting in touch and for your interest. This only works with OpenFOAM v3.0+ (which is a specific version of OpenFOAM, not any version 3 or greater).

I'm so sorry to trouble you again. 
Using the code "cd ~
python -c "import pyDemFoam; print pyDemFoam.__version__"", I tested the pydemfoam. But  the error is as follows:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zy/.local/lib/python2.7/site-packages/pyDemFoam/__init__.py", line 3, in <module>
    from _pyDemFoam import pyDemIcoFoam, pyDemSimpleFoam
ImportError: /home/zy/.local/lib/python2.7/site-packages/_pyDemFoam.so: undefined symbol: _ZN4Foam9UIPstream4readERi
could you give me some suggestion to solve this problem?

**Comment by Yu-Zhang0714** [comment]
> Hi, thanks for getting in touch and for your interest. This only works with OpenFOAM v3.0+ (which is a specific version of OpenFOAM, not any version 3 or greater).

And I think the pydemfoam was not bulit. Because when I input the code
"python setup.py install --user",
the result is:
building version 2016.06.09
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing /home/zy/.local/lib/python2.7/site-packages/pyDemFoam-2016.06.09.egg-info
Writing /home/zy/.local/lib/python2.7/site-packages/pyDemFoam-2016.06.09.egg-info
But the paraview and openfoam v3.0+ have  been installed successfully and they work well . I have no idea what causes this issue.

**Comment by jkfurtney** [comment]
This looks like a runtime linker error. Double check you did these steps:

Add the following line to the end of: `~/.bashrc`

`source $HOME/OpenFOAM/OpenFOAM-v3.0+/etc/bashrc WM_NCOMPPROCS=4 WM_MPLIB=SYSTEMOPENMPI`

To load these changes: `source ~/.bashrc`

**Comment by Yu-Zhang0714** [comment]
> This looks like a runtime linker error. Double check you did these steps:
> 
> Add the following line to the end of: `~/.bashrc`
> 
> `source $HOME/OpenFOAM/OpenFOAM-v3.0+/etc/bashrc WM_NCOMPPROCS=4 WM_MPLIB=SYSTEMOPENMPI`
> 
> To load these changes: `source ~/.bashrc`

Hi, excuse me for coming back.
According to your suggestion, first, I input the code "gedit ~/.bashrc".
Second I add the command "source $HOME/OpenFOAM/OpenFOAM-v3.0+/etc/bashrc WM_NCOMPPROCS=4 WM_MPLIB=SYSTEMOPENMPI`" to the end , like this.


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
source $HOME/OpenFOAM/OpenFOAM-v3.0+/etc/bashrc WM_NCOMPPROCS=4 WM_MPLIB=SYSTEMOPENMPI
source $HOME/OpenFOAM/OpenFOAM-v3.0+/etc/bashrc WM_LABEL_SIZE=64

But it not works, and this problem has not been solved.  I want to ask if I have added the command to the correct position. 
And then, I tried to delete the file "_pyDemFoam.so", and the error became  " no pydemfoam module ", so I think the problem is on the file "_pyDemFoam.so".

**Comment by alisheikholeslam** [comment]
Hello,
how to solve the error below while pyDEMFoam installation:
"Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    assert os.path.isfile(os.getenv("FOAM_APPBIN")+"/icoFoam"), "Cannot find OpenFOAM binaries. Did you build OpenFOAM in the default location? "
AssertionError: Cannot find OpenFOAM binaries. Did you build OpenFOAM in the default location? 
"

**Comment by jkfurtney** [comment]
Did you run this command in the terminal before doing anything?
`source $HOME/OpenFOAM/OpenFOAM-v3.0+/etc/bashrc WM_NCOMPPROCS=4 WM_MPLIB=SYSTEMOPENMPI`

It looks like maybe some environmental variables are not defined? Check what `os.getenv("FOAM_APPBIN")` is returning and make sure there are OpenFOAM binaries there?

**Comment by alisheikholeslam** [comment]
thank you

**Comment by Robert-CFD** [comment]
Hello,
Thank you for your code and documentation. I am new to OF and I also got the error when installing  pyDEMFoam:
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    assert os.path.isfile(os.getenv("FOAM_APPBIN")+"/icoFoam"), "Cannot find OpenFOAM binaries. Did you build OpenFOAM in the default location? "
AssertionError: Cannot find OpenFOAM binaries. Did you build OpenFOAM in the default location? 

I checked my FOAM_APPBIN, and it is 
/home/rs/OpenFOAM/OpenFOAM-v3.0+/platforms/linux64GccDPInt32Opt/bin
My installation directory of OF is:  ~/OpenFOAM/OpenFOAM-v3.0+
Anything wrong with my installation.
Thank you for your help!

**Comment by jkfurtney** [comment]
Hi Robert,

Did you run this command in the terminal before trying to build pyDEMFoam?

`source $HOME/OpenFOAM/OpenFOAM-v3.0+/etc/bashrc WM_NCOMPPROCS=4 WM_MPLIB=SYSTEMOPENMPI`

**Comment by pfcnew** [comment]
Hello,Thanks for your code and documentation. I  got the error when launching the coupled calculation.


/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v3.0+                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
Build  : v3.0+-e941ee6c15e9
Exec   : demIcoFoam
Date   : Dec 02 2020
Time   : 16:59:55
Host   : "denghao-virtual-machine"
PID    : 5514
Case   : /home/denghao/PFC3D_OpenFOAM/dropTest1
nProcs : 1
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
creating demIcoFoam object


PISO: Operating solver in PISO mode

cleaning up socket
Traceback (most recent call last):
  File "cfd_dropTest1.py", line 33, in <module>
    print "send finished"
  File "/home/denghao/.local/lib/python2.7/site-packages/itasca/main.py", line 641, in __exit__
    self.close()
  File "/home/denghao/.local/lib/python2.7/site-packages/itasca/main.py", line 633, in close
    self.socket.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 107] Transport endpoint is not connected


Could you help me? I need your help.

**Comment by Python-Zhou** [comment]
> Hello,Thanks for your code and documentation. I got the error when launching the coupled calculation.
> 
> /_---------------------------------------------------------------------------_ | ========= | | | \ / F ield | OpenFOAM: The Open Source CFD Toolbox | | \ / O peration | Version: v3.0+ | | \ / A nd | Web: [www.OpenFOAM.com](http://www.OpenFOAM.com) | | \/ M anipulation | | *---------------------------------------------------------------------------*/ Build : v3.0+-e941ee6c15e9 Exec : demIcoFoam Date : Dec 02 2020 Time : 16:59:55 Host : "denghao-virtual-machine" PID : 5514 Case : /home/denghao/PFC3D_OpenFOAM/dropTest1 nProcs : 1 sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE). fileModificationChecking : Monitoring run-time modified files using timeStampMaster allowSystemOperations : Allowing user-supplied system call operations
> 
> // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * // creating demIcoFoam object
> 
> PISO: Operating solver in PISO mode
> 
> cleaning up socket Traceback (most recent call last): File "cfd_dropTest1.py", line 33, in print "send finished" File "/home/denghao/.local/lib/python2.7/site-packages/itasca/main.py", line 641, in **exit** self.close() File "/home/denghao/.local/lib/python2.7/site-packages/itasca/main.py", line 633, in close self.socket.shutdown(socket.SHUT_RDWR) File "/usr/lib/python2.7/socket.py", line 228, in meth return getattr(self._sock,name)(*args) socket.error: [Errno 107] Transport endpoint is not connected
> 
> Could you help me? I need your help.

Hello, pfcnew,

Have you ever iuused this question? I also met it.
